In [226]:
import numpy as np

In [227]:
#Task1.1

import time
size_of_vec = 10000000

def python():
    start = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [2*X[i]**2 + 4*Y[i] for i in range(len(X))]
    return time.time() - start

def numpy():
    start = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = 2*X**2 + 4*Y
    return time.time() - start

print("Numpy is {} times faster!".format(python()/numpy()))

Numpy is 60.04997813550815 times faster!


Результаты измерений для функции z = 2*x** 2 + 4*y:

Numpy is 58.36340254877714 times faster!

Numpy is 60.76030890058083 times faster!

Numpy is 61.75725698268953 times faster!

Numpy is 58.182957538879364 times faster!

Numpy is 59.09626096427876 times faster!

#### В среднем numpy в 59,6320373870411248‬ раз быстрее

In [228]:
#Task1.2

import time
n = 1000

def m_mult(a, b, n): #вспомогательная функция для перемножения двух матриц
    s = 0 
    tmp = []
    ans = []
    for z in range(0, n):
        for j in range(0, n):
            for i in range(0, n):
                s = s + a[z][i] * b[i][j]
            tmp.append(s)
            s=0
        ans.append(tmp)
        tmp=[]           
    return ans


def python():
    start = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [2*X[i]**2 + 4*Y[i] for i in range(len(X))]
    return time.time() - start

def numpy():
    start = time.time()
    X = np.random.random((n, n))
    Y = np.random.random((n, n))
    Z = X @ X
    return time.time() - start

print("Numpy is {} times faster!".format(python()/numpy()))

Numpy is 201.9722181707865 times faster!


Резульаты измерений для перемножения двух матриц:

Numpy is 162.7192767499256 times faster!

Numpy is 196.3484281027884 times faster!

Numpy is 189.02572759718464 times faster!

Numpy is 197.8073459067924 times faster!

Numpy is 191.12784879349238 times faster!

#### В среднем numpy в 187,405725430036684‬‬ раз быстрее

In [229]:
#Task2

a = np.random.randint(2, 75, size=10)
print("начальный массив:", a)
print("нечётные числа:", a[a % 2 != 0])
print("заменим нечётные на -1:", np.where(a % 2 != 0, -1, a))

начальный массив: [40  8 35  9 25 67 46 69 33 28]
нечётные числа: [35  9 25 67 69 33]
заменим нечётные на -1: [40  8 -1 -1 -1 -1 46 -1 -1 28]


In [230]:
#Task3

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([2, 4, 6, 8, 545])
print("для a и b:", np.setdiff1d(a,b))

A = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
B = np.array([1, 2, 30, 90])
print("для A и B:", np.setdiff1d(A, B))

для a и b: [ 1  3  5  7  9 10]
для A и B: [10 20 40 50 60 70 80]


In [231]:
#Task4
import random

s = random.randint(10, 101) 
print("размер матрицы:", s)
a = np.random.random((s, s)) #создаём матрицу
print(a)

print("максимальный элемент:", np.max(a))
print("сумма элементов:", np.sum(a))

print(a/np.max(a)) #делим все элементы матрицы на максимальный элемент


print("вычли среднее значение по строкам:")
print(a - a.mean(axis=1, keepdims=True))

print("заменим максимум на -1:")
print(np.where(a == np.max(a), -1, a))

размер матрицы: 46
[[0.00549913 0.2372654  0.10616595 ... 0.28937674 0.76025058 0.03162209]
 [0.98077784 0.00633145 0.44577774 ... 0.59952475 0.47784173 0.7381363 ]
 [0.38838202 0.73635001 0.54606031 ... 0.62944395 0.87440648 0.82273554]
 ...
 [0.30754906 0.0633387  0.08115929 ... 0.9209117  0.33617914 0.48901356]
 [0.65328946 0.06899451 0.78910111 ... 0.22709229 0.66398227 0.49959935]
 [0.57954587 0.23585365 0.6290891  ... 0.66648433 0.63177133 0.06565255]]
максимальный элемент: 0.9997440388256145
сумма элементов: 1066.8592510296326
[[0.00550054 0.23732614 0.10619314 ... 0.28945082 0.76044523 0.03163019]
 [0.98102895 0.00633307 0.44589187 ... 0.59967825 0.47796407 0.73832529]
 [0.38848145 0.73653853 0.54620011 ... 0.6296051  0.87463035 0.82294619]
 ...
 [0.3076278  0.06335492 0.08118007 ... 0.92114748 0.33626521 0.48913876]
 [0.65345672 0.06901217 0.78930314 ... 0.22715043 0.66415227 0.49972726]
 [0.57969425 0.23591403 0.62925016 ... 0.66665496 0.63193308 0.06566936]]
вычли среднее зн

In [232]:
#Task5

def nan_to_mean(a):
    m = np.nanmean(a)
    if (np.isnan(m) == 1):
        return np.zeros(shape=a.shape)
    return np.where(np.isnan(a) == 1, m, a)

a = np.array([np.nan, 5, np.nan, 12])
print("до:", a)
print("после:", nan_to_mean(a)) 

b = np.array([np.nan, np.nan, np.nan])
print("до:", b)
print("после:", nan_to_mean(b))    

до: [nan  5. nan 12.]
после: [ 8.5  5.   8.5 12. ]
до: [nan nan nan]
после: [0. 0. 0.]


C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: Mean of empty slice
  after removing the cwd from sys.path.


In [233]:
#Task6

def normalizing(a):
    return (a - np.min(a)) / (np.max(a) - np.min(a))

a = np.array([0, 2, 10])
print("исходный:", a)
print("нормализованный:", normalizing(a))

исходный: [ 0  2 10]
нормализованный: [0.  0.2 1. ]


In [234]:
#Task7

a = np.random.randint(1, 100, size=8)
print("исходный:", a)
np.savetxt('file.txt', a)
b = np.loadtxt('file.txt')
print("исходный записанный и считанный:", b)

исходный: [38 51 31 11 26 24 21 66]
исходный записанный и считанный: [38. 51. 31. 11. 26. 24. 21. 66.]


In [235]:
#Task8

a = np.random.randint(1, 101, size=10)
v = random.randint(1, 101)
print("массив:", a)
print("значение:", v)  
print("ближайшее к этому значению:", a[(np.abs(a - v)).argmin()])

массив: [11 26 86 47 30 16 25 14 94 86]
значение: 62
ближайшее к этому значению: 47


In [236]:
#Task9

def m_frame(n, m, inside, frame):
    a = np.full((n, m), inside)
    i = np.array([0, n-1])
    j = np.array([0, m-1])
    a[i, :] = a[:, j] = frame
    return a

print(m_frame(5, 8, 1, 0))

[[0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0]]


In [237]:
#Task10

def colomn_sort (a, col):
    return a[np.argsort(a[:, col-1])]

a = np.array([[1, 2, 9], [2, 1, -1], [6, 0, 3]])
print("исходный\n", a)
print("сорт. по 2 столбцу\n", colomn_sort(a, 2))
print("сорт. по 3 столбцу\n", colomn_sort(a, 3))

исходный
 [[ 1  2  9]
 [ 2  1 -1]
 [ 6  0  3]]
сорт. по 2 столбцу
 [[ 6  0  3]
 [ 2  1 -1]
 [ 1  2  9]]
сорт. по 3 столбцу
 [[ 2  1 -1]
 [ 6  0  3]
 [ 1  2  9]]


In [238]:
#Task11

def chessboard(n):
    a = np.zeros((n, n))
    a[1::2,::2] = 1
    a[::2,1::2] = 1
    return a

print(chessboard(5))

[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


In [269]:
#Task12

def next_stage(a):
    n = np.zeros(a.shape, dtype=int)
    n[1:, 1:] += a[:-1, :-1]
    n[1:, :-1] += a[:-1, 1:]
    n[:-1, 1:] += a[1:, :-1]
    n[:-1, :-1] += a[1:, 1:]
    n[:-1, :] += a[1:, :]
    n[1:, :] += a[:-1, :]
    n[:, :-1] += a[:, 1:]
    n[:, 1:] += a[:, :-1]
    tmp1 = ((a == 1) & (n < 4) & (n > 1))
    tmp2 = ((a == 0) & (n == 3))
    print(n)
    a = (tmp1 | tmp2).astype(int)
    return a

a = np.array([[0, 0, 0, 0, 0],
              [0, 0, 1, 0, 0],
              [0, 0, 1, 0, 0],
              [0, 0, 1, 0, 0],
              [0, 0, 0, 0, 0]])

print(a)
for i in range(3): 
    print(next_stage(a))

[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]
[[0 1 1 1 0]
 [0 2 1 2 0]
 [0 3 2 3 0]
 [0 2 1 2 0]
 [0 1 1 1 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 1 1 1 0]
 [0 2 1 2 0]
 [0 3 2 3 0]
 [0 2 1 2 0]
 [0 1 1 1 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 1 1 1 0]
 [0 2 1 2 0]
 [0 3 2 3 0]
 [0 2 1 2 0]
 [0 1 1 1 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
